server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simpledemo?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

shiro:
  loginUrl: /login